version: "3.8"
services:
  gmd-node-service:
    image: coopnetwork/gmd-node
    container_name: gmd-node-service
    ports:
      - 6874:6874
    volumes:
      - conf:/GMD-blockchain/conf:z
      - nxt_db:/GMD-blockchain/nxt_db:z
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1
  reverse-proxy:
    image: coopnetwork/gmd-reverse-proxy-ng
    ports:
      - 443:443
    volumes:
      - /etc/cert/fullchain.pem:/etc/nginx/fullchain.pem
      - /etc/cert/privkey.pem:/etc/nginx/privkey.pem  
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1

volumes:
    conf: {}
    nxt_db: {}
